### ISSUE TITLE
Great work

### ISSUE THREAD

**Issue by rljacobson** [ebkalderon/nix-language-server#13]
This is some really great code. You have written a model example of a serious parser using Nom. It surely hasn't escaped you that most of your parser code is generic. It would be a fun exercise to write a PEG parser generator that outputs a parser using this code. 

Just wanted to drop you a note to express my appreciation for the quality of this code base. Feel free to close the issue.

**Comment by ebkalderon** [comment]
Thank you so much for the kind words, @rljacobson! It is truly a pleasant surprise to see this on a codebase that I, frankly, haven't been frequently updating as of late, and I honestly don't know what I'm doing (just a personal hobby and research project). I have considered the possibility of writing a PEG parser using these techniques to produce equivalent or close-to-equivalent parser combinator code as well, but haven't actively pursued this. I know that I was previously working on revamping the code you see here in `nix-parser` using a lossless concrete syntax tree (CST) approach in `nix-parser2`, while still sharing many of the same core principles, but haven't really gotten started on it. Nevertheless, I do hope this code may have been of some use to you anyways. Thanks again for the unexpected compliment! Hope you're having a lovely day/night. 😉
